version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0 

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Test
          xcode-version: "12.2.0"
          workspace: WordPressAuthenticator.xcworkspace
          scheme: WordPressAuthenticator
          device: iPhone 11
          ios-version: "14.2"
          bundle-install: true
          pod-install: true
      - ios/validate-podspec:
          name: Validate Podspec
          xcode-version: "12.2.0"
          podspec-path: WordPressAuthenticator.podspec
          bundle-install: true
      - ios/publish-podspec:
          name: Publish to Trunk
          xcode-version: "12.2.0"
          podspec-path: WordPressAuthenticator.podspec
          bundle-install: true
          post-to-slack: true
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
